/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-28 21:45:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_005femp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Register</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap.css\">\r\n");
      out.write("\t    <style>\r\n");
      out.write("        .conatiners{\r\n");
      out.write("                  margin-left: 420px; \r\n");
      out.write("                  margin-top: 10x;\r\n");
      out.write("                  background-color: aqua;\r\n");
      out.write("                  border-radius: 20px;\r\n");
      out.write("                  width: 470px;\r\n");
      out.write("                  padding: 30px;\r\n");
      out.write("                }\r\n");
      out.write("                h1:hover{color: red; cursor: pointer;}\r\n");
      out.write("                h1{color: orange; background-color: }\r\n");
      out.write("                h2{color: blue; text-align: center; cursor: pointer;}\r\n");
      out.write("                h2:hover{color: black;}\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<h1 class=\"text-center\">WELCOME TO AITI-KACE JAVA ENTERPRISE REGISTRATION WEBSITE</h1>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"conatiners\">\r\n");
      out.write("\r\n");
      out.write("        <h2>USER REGISTRATION</h2>\r\n");
      out.write("        <hr>\r\n");
      out.write("       \r\n");
      out.write("    \r\n");
      out.write("    <form action=\"register.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> EMPLOYEE ID :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"empid\" class=\"form-control\" placeholder=\"Enter employee id\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> MANAGER ID :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"managerid\" class=\"form-control\" placeholder=\"Enter manager id\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>DEPT NO :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"deptid\" class=\"form-control\" placeholder=\"Enter dept no\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> USERNAME :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"user\" class=\"form-control\" placeholder=\"Enter username\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> EMAIL :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"email\" name=\"email\" class=\"form-control\" placeholder=\"Enter email\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>MOBILE :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"number\" name=\"mobile\" class=\"form-control\" placeholder=\"Enter your phone\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> ADDRESS :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"address\" class=\"form-control\" placeholder=\"Enter address\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> EDUCATION :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"education\" class=\"form-control\" placeholder=\"Enter your education\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>PASSWORD :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"pass\" class=\"form-control\" placeholder=\"Enter password\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th> <input type=\"checkbox\" name=\"i_agree\" value=\"i_agree\" required> I Agree</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr class=\"text-right\">\r\n");
      out.write("                <td> <input type=\"submit\" class=\"btn btn-primary\" value=\"Submit\"> </td>\r\n");
      out.write("                <td> <input type=\"reset\" class=\"btn btn-danger\" value=\"Reset\"> </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("            \t\r\n");
      out.write("              <td> <p class=\"text-center\">Already have an Account? <a href=\"loginform.html\">Login</a></p> </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
