/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-02-02 20:40:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;

public final class viewprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>View Profile</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");


try{
	
	//String id = (String)session.getAttribute("empid");
	
	Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "catalyst1006");
	
	PreparedStatement ps = conn.prepareStatement("select ems_details.empid, ems_details.address, ems_details.education, ems_details.mobile, ems_details.deptno, ems_details.manager_id, ems_login.user, ems_login.pass, ems_login.email, leave_table.leaveid, leave_table.applydate, leave_table.reasons, leave_table.resumedate FROM ems_details, ems_login, leave_table WHERE ems_details.empid = leave_table.empid ORDER BY ems_details.empid");

	
	//ps.setString(1,);
	ResultSet rs = ps.executeQuery();
	
	while(rs.next()) {
		
		
		out.println("<h2> EMPLOYEE PROFILE </h2>");
		
//out.println("<table> <tr><th> EMPLOYEE ID </th><th> ADDRESS </th><th> ADDRESS </th><th> EDUCATION </th><th> MOBILE </th><th> DEPT ID </th><th> MANAGER ID </th><th> LEAVE ID </th><th> APPLY DATE </th><th> RESUME DATE </th></tr> <tr><td>  </td></tr>  </table>");
		
		out.println("EMPLOYEE ID : " + " " + rs.getString("empid") + "<br/>" + "<br/>");
		
		out.println("ADDRESS : " + " " + rs.getString("address") + "<br/>" + "<br/>");
		
		out.println("EDUCATION : " + " " + rs.getString("education") + "<br/>" + "<br/>");
		
		out.println("MOBILE : " + " " + rs.getString("mobile") + "<br/>" + "<br/>");
		
		out.println("DEPT ID : " + " " + rs.getString("deptno") + "<br/>" + "<br/>");
		
		out.println("MANAGER ID : " + " " + rs.getString("manager_id") + "<br/>" + "<br/>");
		
		out.println("USER NAME : " + " " + rs.getString("user") + "<br/>" + "<br/>");
		
		out.println("PASSWORD : " + " " + rs.getString("pass") + "<br/>" + "<br/>");
		
		out.println("EMAIL : " + " " + rs.getString("email") + "<br/>" + "<br/>");
		
		out.println("LEAVE ID : " + " " + rs.getString("leaveid") + "<br/>" + "<br/>");
		
		out.println("APPLY DATE : " + " " + rs.getString("applydate") + "<br/>" + "<br/>");
		
		out.println("REASONS : " + " " + rs.getString("reasons") + "<br/>" + "<br/>");
		
		out.println("RESUME DATE : " + " " + rs.getString("resumedate"));
		
		
	}
	

}

catch (Exception e) {

	out.println(e.getMessage());
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<br/> <br/>\r\n");
      out.write("<a href=\"userpage1.jsp\"> Return to UserPage </a>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
